name: Build Goregram

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@main
        with:
          ref: Goregram
          submodules: true

      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 30

      - uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install required dependencies
        run: |
          sudo apt install meson gperf

      - name: Remove prebuilt binaries 
        run: |
          find . -type f -wholename '*.a' -delete

      - name: Build
        run: |
          ./gradlew assembleAfatRelease
          mv TMessagesProj_App/build/outputs/apk/afat/release/app.apk app-release.apk

      - name: Create logs
        if: always()
        run: |
          tar --create --file=- '/var/tmp/obggcc' | xz --threads='0' --compress -9 > '/tmp/logs.tar.xz'

      - name: Upload logs
        if:  always()
        uses: actions/upload-artifact@main
        with:
          name: logs
          if-no-files-found: error
          path: |
              /tmp/logs.tar.xz

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: build-clang
          path: app-release.apk
          archive: false
